/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.4.2.qualifier
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package com.mycompany.commonTypes;


/**
 * 
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class AvailabilityStatusEnum
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"0"'
     *  
     *
     * 
     */
    public final static String unknown = "0";


    /**
     * 
     * @tigerstripe.label
     *  value = '"1"'
     *  
     *
     * 
     */
    public final static String available = "1";


    /**
     * 
     * @tigerstripe.label
     *  value = '"2"'
     *  
     *
     * 
     */
    public final static String underRepair = "2";

}