/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.3.0.v200806301337_incubation
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package com.mycompany.commonTypes;


/**
 * An enumeration used to define the units of measure for a given attribute value (e.g., Bits, Bytes, Seconds, Minutes).
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="int"
 *      extensible="false"
 * @tigerstripe.interface package = "com.mycompany"
 *      generate = "true"
 * * 
 */
public abstract class UnitsEnum
 {


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '0'
     *  
     *
     * 
     */
    public final static int Bits = 0;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '1'
     *  
     *
     * 
     */
    public final static int Bytes = 1;


    /**
     * time
     * @tigerstripe.label
     *  value = '2'
     *  
     *
     * 
     */
    public final static int Seconds = 2;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '3'
     *  
     *
     * 
     */
    public final static int Characters = 3;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '4'
     *  
     *
     * 
     */
    public final static int Bits_Per_Second = 4;


    /**
     * time
     * @tigerstripe.label
     *  value = '5'
     *  
     *
     * 
     */
    public final static int Minutes = 5;


    /**
     * angle
     * @tigerstripe.label
     *  value = '6'
     *  
     *
     * 
     */
    public final static int Degrees = 6;


    /**
     * temperature
     * @tigerstripe.label
     *  value = '7'
     *  
     *
     * 
     */
    public final static int tempCentigrade = 7;


    /**
     * temperature
     * @tigerstripe.label
     *  value = '8'
     *  
     *
     * 
     */
    public final static int tempFahrenheit = 8;


    /**
     * frequency
     * @tigerstripe.label
     *  value = '9'
     *  
     *
     * 
     */
    public final static int Hertz = 9;


    /**
     * length
     * @tigerstripe.label
     *  value = '10'
     *  
     *
     * 
     */
    public final static int Meters = 10;


    /**
     * length
     * @tigerstripe.label
     *  value = '11'
     *  
     *
     * 
     */
    public final static int MilliMeters = 11;


    /**
     * current
     * @tigerstripe.label
     *  value = '12'
     *  
     *
     * 
     */
    public final static int MilliAmps = 12;


    /**
     * voltage
     * @tigerstripe.label
     *  value = '13'
     *  
     *
     * 
     */
    public final static int MilliVolts = 13;


    /**
     * power
     * @tigerstripe.label
     *  value = '14'
     *  
     *
     * 
     */
    public final static int Watts = 14;


    /**
     * energy
     * @tigerstripe.label
     *  value = '15'
     *  
     *
     * 
     */
    public final static int Watt_Hours = 15;


    /**
     * dimensionless ratio
     * @tigerstripe.label
     *  value = '16'
     *  
     *
     * 
     */
    public final static int Percentage = 16;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '17'
     *  
     *
     * 
     */
    public final static int Cells = 17;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '18'
     *  
     *
     * 
     */
    public final static int Cells_Per_Second = 18;


    /**
     * time
     * @tigerstripe.label
     *  value = '19'
     *  
     *
     * 
     */
    public final static int Tenths_Of_MicroSeconds = 19;


    /**
     * length
     * @tigerstripe.label
     *  value = '20'
     *  
     *
     * 
     */
    public final static int Inches = 20;


    /**
     * power ratio
     * @tigerstripe.label
     *  value = '21'
     *  
     *
     * 
     */
    public final static int Decibels = 21;


    /**
     * dimensionless ratio
     * @tigerstripe.label
     *  value = '22'
     *  
     *
     * 
     */
    public final static int Parts_Per_Million = 22;


    /**
     * angle
     * @tigerstripe.label
     *  value = '23'
     *  
     *
     * 
     */
    public final static int Radians = 23;


    /**
     * pressure
     * @tigerstripe.label
     *  value = '24'
     *  
     *
     * 
     */
    public final static int mmHg = 24;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '25'
     *  
     *
     * 
     */
    public final static int Packets = 25;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '26'
     *  
     *
     * 
     */
    public final static int Packets_Per_Second = 26;


    /**
     * 
     * @tigerstripe.label
     *  value = '27'
     *  
     *
     * 
     */
    public final static int Percentage_Of_RawBandwidth = 27;


    /**
     * 
     * @tigerstripe.label
     *  value = '28'
     *  
     *
     * 
     */
    public final static int Percentage_Of_RemainingBandwidth = 28;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '29'
     *  
     *
     * 
     */
    public final static int Bytes_Per_Second = 29;


    /**
     * 
     * @tigerstripe.label
     *  value = '30'
     *  
     *
     * 
     */
    public final static int ElementCount = 30;


    /**
     * length
     * @tigerstripe.label
     *  value = '31'
     *  
     *
     * 
     */
    public final static int centimeters = 31;


    /**
     * 
     * @tigerstripe.label
     *  value = '32'
     *  
     *
     * 
     */
    public final static int dBm_Per_Hz = 32;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '33'
     *  
     *
     * 
     */
    public final static int kilobits_Per_Second = 33;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '34'
     *  
     *
     * 
     */
    public final static int kiloBytes = 34;


    /**
     * rate of information flow
     * @tigerstripe.label
     *  value = '35'
     *  
     *
     * 
     */
    public final static int megabits_Per_Second = 35;


    /**
     * amount of information
     * @tigerstripe.label
     *  value = '36'
     *  
     *
     * 
     */
    public final static int megaBytes = 36;


    /**
     * frequency
     * @tigerstripe.label
     *  value = '37'
     *  
     *
     * 
     */
    public final static int megaHertz = 37;


    /**
     * time
     * @tigerstripe.label
     *  value = '38'
     *  
     *
     * 
     */
    public final static int milliseconds = 38;


    /**
     * weight (mass)
     * @tigerstripe.label
     *  value = '39'
     *  
     *
     * 
     */
    public final static int kilograms = 39;


    /**
     * weight (mass)
     * @tigerstripe.label
     *  value = '40'
     *  
     *
     * 
     */
    public final static int pounds = 40;


    /**
     * length
     * @tigerstripe.label
     *  value = '41'
     *  
     *
     * 
     */
    public final static int feet = 41;

}