/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.7.0.201106092111
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package com.mycompany;


/**
 * 
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="int"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 * * 
 */
public abstract class Enum
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '0'
     *  
     *
     * 
     */
    public final static int literal = 0;

}