/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.7.0.201107012345
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package com.mycompany;


/**
 * 
 *
 * @tigerstripe.managedEntity primary-key="String"
 *      extensibilityType="multi"
 *      isSessionFactoryMethods="false"
 *		isAbstract = "false"
 *		implements = ""
 * @tigerstripe.key-interface package = "com.mycompany"
 *      generate = "true"
 * @tigerstripe.value package = "com.mycompany"
 *      generate = "true"
 *
 * @tigerstripe.property ts.id="ossj.entity.create"
 *   byAutoNaming = "false"
 *   bulkBestEffort = "false"
 *   ts.id = "ossj.entity.create"
 *   bulkAtomic = "false"
 *   bulkAtomicByKeys = "false"
 *   bulkBestEffortByKeys = "false"
 *   simple = "true"
 *
 * @tigerstripe.property ts.id="ossj.entity.get"
 *   byTemplates = "false"
 *   ts.id = "ossj.entity.get"
 *   byTemplate = "false"
 *   bulkAtomicByKeys = "false"
 *   simpleByKey = "true"
 *
 * @tigerstripe.property ts.id="ossj.entity.set"
 *   ts.id = "ossj.entity.set"
 *   simple = "true"
 *   byTemplates = "false"
 *   byTemplate = "false"
 *   byTemplatesBestEffort = "false"
 *   byTemplateBestEffort = "false"
 *   bulkAtomic = "false"
 *   bulkBestEffort = "false"
 *   bulkAtomicByKeys = "false"
 *   bulkBestEffortByKeys = "false"
 *
 * @tigerstripe.property ts.id="ossj.entity.remove"
 *   byTemplates = "false"
 *   byTemplatesBestEffort = "false"
 *   ts.id = "ossj.entity.remove"
 *   byTemplate = "false"
 *   bulkAtomicByKeys = "false"
 *   bulkBestEffortByKeys = "false"
 *   simpleByKey = "true"
 *   byTemplateBestEffort = "false"
 *
 * 
 */
public abstract class Entity1
 {



    /**
     * 
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *   ref-by = "value"
     *
     *
     * 
     */
	public String attribute0;



    /**
     * 
     * @tigerstripe.label
     *  value = '"0"'
     *  
     *
     * 
     */
    public final static String literal0 = "0";



    /**
     * 
     * @tigerstripe.method 
     *  iteratorReturn = "false"
     *  isOptional = "false"
	 *  isAbstract = "false"
     *  isOrdered = "false"
     *  isUnique = "false"
     *  typeMultiplicity = "0..1"
     *  returnName = ""
     *  visibility = "public"
     *
     * 
     * @tigerstripe.property ts.id = "ossj.method"
     *   simple = "true"
     *   byTemplates = "false"
     *   byTemplatesBestEffort = "false"
     *   byTemplate = "false"
     *   byTemplateBestEffort = "false"
     *   simpleByKey = "false"
     *   bulkAtomic = "false"
     *   bulkBestEffort = "false"
     *   instanceMethod = "true"
     *   bulkAtomicByKeys = "false"
     *   bulkBestEffortByKeys = "false"
     *
     */
	public abstract void method0(
			)
		;
}