/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.5.0.201001061511
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package simple;


/**
 * 
 *
 * @tigerstripe.associationClass
 *		isAbstract = "false"
 *		implements = ""
 *
 * * 
 */
public abstract class AssociationClass1
 {

	/**
 * 
	 *	@tigerstripe.association-aEnd
	 *    aggregation = "none"
	 *    changeable = "none"
	 *    multiplicity = "1"
	 *    isOrdered = "false"
	 *    isUnique = "false"
	 *    isNavigable = "false"
	 *
	 * 
	 */	
	public simple.Ent3 ent3_0 = null;
	
	/**
 * 
	 *	@tigerstripe.association-zEnd
	 *    aggregation = "none"
	 *    changeable = "none"
	 *    multiplicity = "1"
	 *    isOrdered = "false"
	 *    isUnique = "false"
	 *    isNavigable = "true"
	 *
 *
 * 
	 */	
	public simple.Ent1 ent1_1 = null;
	

	
}