<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core"
    nsURI="http:///org/eclipse/tigerstripe/espace/core.ecore" nsPrefix="org.eclipse.tigerstripe.espace.core">
  <eClassifiers xsi:type="ecore:EEnum" name="Mode">
    <eLiterals name="ReadWrite"/>
    <eLiterals name="ReadOnly" value="1"/>
    <eLiterals name="ReadOnlyOverride" value="2"/>
  </eClassifiers>
</ecore:EPackage>
