<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tree"
    nsURI="http:///org/eclipse/tigerstripe/espace/core/tree.ecore" nsPrefix="org.eclipse.tigerstripe.espace.core.tree">
  <eClassifiers xsi:type="ecore:EClass" name="ITree" instanceClassName="org.eclipse.tigerstripe.espace.core.tree.ITree"
      abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RBNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//RBNode"
        transient="true" eOpposite="#//RBNode/childElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childElements" upperBound="-1"
        eType="#//RBNode" containment="true" resolveProxies="false" eOpposite="#//RBNode/parent"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="childLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RBTree" eSuperTypes="#//ITree">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//RBNode"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
