/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.0.7.0.201102281826
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package test_new;


/**
 * 
 *
 * @tigerstripe.event
 *      isSingleExtensionType="false"
 *		isAbstract = "false"
 *		implements = ""
 *
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 * * 
 */
public class Event
 {



    /**
     * 
     * @tigerstripe.label
     *  value = '"0"'
     *  
     *
     * @tigerstripe.stereotype st.name = "ST_for_Literal"
     * 
     */
    public final static java.lang.String literal0 = "0";



    /**
     * 
     * @tigerstripe.field 
     *  isOptional = "false"
     *  isReadOnly = "false"
     *  isOrdered = "false"
     *  isUnique = "true"
     *  typeMultiplicity = "1"
     *   ref-by = "value"
     *
     *
     * 
     */
	public String attribute0;

}