/*******************************************************************************
 * Copyright (c) 2008 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Cisco Systems, Inc. - erdillon
 *******************************************************************************/
package org.eclipse.tigerstripe.releng.downloadsite.ant.types;

import org.eclipse.tigerstripe.releng.downloadsite.schema.Bundle;
import org.eclipse.tigerstripe.releng.downloadsite.schema.Component;
import org.eclipse.tigerstripe.releng.downloadsite.schema.DownloadSiteFactory;
import org.eclipse.tigerstripe.releng.downloadsite.schema.impl.ComponentImpl;

/**
 * This is provided to allow the use of the EMF generated classes directly from
 * an Ant task. The "createXXXX()" method allows Ant to construct the inner
 * types as it encounters them.
 * 
 * The rest of the interface as generated by EMF matches completely.
 * 
 * @author erdillon
 * 
 */
public class AntComponent extends ComponentImpl implements Component {

	public Bundle createBundle() {
		Bundle result = DownloadSiteFactory.eINSTANCE.createBundle();
		getBundle().add(result);
		return result;
	}
}
